version: '3'
services:
 web:
   container_name: docker-django
   build: .
   command: python manage.py runserver 0.0.0.0:8000
   working_dir: /code
   ports:
     - 8000:8000
   volumes:
     - .:/code
   depends_on:
     - db
 db:
   container_name: docker-django-db
   image: mysql:5.7
   restart: always
   environment:
     MYSQL_DATABASE: docker_django
     MYSQL_USER: root
     MYSQL_PASSWORD: password
     MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
   volumes:
     - ./mysql:/var/lib/mysql
   ports:
     - 3306:3306
